In [3]:
import numpy as np
import meshio as mio
import igl
import scipy
from c1_meshing_pipeline import *

In [5]:
ryan_mesh = mio.read("../../build/test_131969/CT_from_lagrange_nodes.msh")
points = ryan_mesh.points
tris = ryan_mesh.cells[0].data

In [25]:
v_upsample_local, f_upsample_local = sample1(0)

In [37]:
# v_smoothed, _, _, f_smoothed, _, _ =igl.read_obj("../../build/test_131969/sampled_after_smoothing.obj")



array([[1.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 0.00000000e+00],
       [4.44089210e-16, 0.00000000e+00],
       [5.55111512e-16, 0.00000000e+00],
       [1.33226763e-15, 0.00000000e+00],
       [4.44089210e-16, 0.00000000e+00],
       [1.11022302e-16, 0.00000000e+00],
       [3.33066907e-16, 0.00000000e+00]])

In [35]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])