In [3]:
import numpy as np
import meshio as mio
import igl
import scipy
from c1_meshing_pipeline import *

In [5]:
ryan_mesh = mio.read("../../build/test_131969/CT_from_lagrange_nodes.msh")
points = ryan_mesh.points
tris = ryan_mesh.cells[0].data

In [25]:
v_upsample_local, f_upsample_local = sample1(0)

In [37]:
# v_smoothed, _, _, f_smoothed, _, _ =igl.read_obj("../../build/test_131969/sampled_after_smoothing.obj")



In [39]:
f = np.array([[1,2,3]])
x = igl.boundary_facets(f)

In [41]:
np.unique(x)

array([1, 2, 3])

In [35]:
np.ones((1,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [36]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])