In [1]:
import numpy as np

In [2]:
a = np.array([1,1,1])
b= np.array([2,2,2])

In [3]:
np.concatenate((a, b))

array([1, 1, 1, 2, 2, 2])

In [4]:
c = np.array([
    [1,2,3],
    [1,2,3],
    [1,2,3]
]
)

In [8]:
np.reshape(c, (c.shape[0]*3, 1)).T[0]

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [10]:
a = np.array([
    [1,1,1],
    [2,2,2],
    [3,3,3]
])

In [11]:
a[[0,2]]

array([[1, 1, 1],
       [3, 3, 3]])

In [12]:
kn = np.array([
    [1,0,0,0,0,0,0],
    [0,1,0,0,0,0,0],
    [-3,0,3,0,0,0,0],
    [0,-3,0,3,0,0,0],
    [0,0,0,0,0,0,0]
])

ce = np.array([-1.5, 1.5, -0.25, 0.25, 0])

In [13]:
ce @ kn

array([-0.75,  0.75, -0.75,  0.75,  0.  ,  0.  ,  0.  ])